<script setup lang="ts">
/**
 * The home page, in four bands: what the library is, the six decisions that shape it, what it
 * guarantees on accessibility and which engines it runs on, and how to install it. Two of the
 * bands are centred and one is not, deliberately; the accessibility band reads down a column
 * beside its accordion, where centring a bulleted argument would only make it harder to follow.
 */
import {
  VButton,
  VChip,
  VIcon,
  VTab,
  VTabPanel,
  VTabs,
  VToggle,
  VToggleItem,
  VTypography,
} from 'vectis-ui'
import { arrow_right_alt as arrowRightAltIcon } from 'vectis-ui/icons'

import chromeLogo from '~/assets/img/chrome-browser-svg.svg'
import edgeLogo from '~/assets/img/edge-browser-svg.svg'
import firefoxLogo from '~/assets/img/firefox-browser-svg.svg'
import safariLogo from '~/assets/img/safari-browser-svg.svg'

import { SITE_NAME, SITE_NPM_URL, SITE_REPO_URL, SITE_URL } from '~/content/site'

const { t } = useI18n()
const localePath = useLocalePath()
const { app } = useRuntimeConfig()

/**
 * The home page's head, and the one place the site tells a search engine what it IS.
 * `Organization` names the PROJECT behind it, and its `sameAs` is what ties this domain, the
 * repository and the published package into one entity instead of three addresses that merely
 * happen to agree.
 */
useHead(() => {
  const title = t('home.documentTitle')
  const description = metaDescription(t('home.heroBody'))
  const home = `${SITE_URL}${localePath('/')}`
  const root = `${SITE_URL}${app.baseURL}`

  return {
    title,
    meta: [
      { name: 'description', content: description },
      { property: 'og:title', content: documentTitle(title) },
      { property: 'og:description', content: description },
    ],
    script: [
      {
        type: 'application/ld+json',
        innerHTML: JSON.stringify({
          '@context': 'https://schema.org',
          '@graph': [
            {
              '@type': 'WebSite',
              '@id': `${home}#website`,
              name: SITE_NAME,
              url: home,
              publisher: { '@id': `${root}#organization` },
            },
            {
              '@type': 'Organization',
              '@id': `${root}#organization`,
              name: SITE_NAME,
              url: root,
              logo: `${root}favicon.svg`,
              sameAs: [SITE_REPO_URL, SITE_NPM_URL],
            },
          ],
        }),
      },
    ],
  }
})

const docsHome = computed(() => localePath('/docs/installation'))

/**
 * The six feature cards, as data: two catalogue keys, an icon, and an accent. The icons come
 * from the SITE's registry (`icons/icons.ts`, regenerated by
 * `pnpm --filter vectis-docs icons`): none of the six is among the 34 the library ships, and
 * the resolver hands an unknown name back to that registry by answering `undefined`.
 */
const cards = [
  { title: 'home.nativeTitle', body: 'home.nativeBody', icon: 'bolt', accent: 'orange' },
  { title: 'home.standardTitle', body: 'home.standardBody', icon: 'public', accent: 'yellow' },
  {
    title: 'home.customizationTitle',
    body: 'home.customizationBody',
    icon: 'palette',
    accent: 'violet',
  },
  { title: 'home.overridesTitle', body: 'home.overridesBody', icon: 'layers', accent: 'green' },
  { title: 'home.ssrTitle', body: 'home.ssrBody', icon: 'dns', accent: 'blue' },
  { title: 'home.iconsTitle', body: 'home.iconsBody', icon: 'interests', accent: 'pink' },
]

/**
 * Where the hover glow sits, and the only JavaScript on this page: a pointer position is the
 * one thing CSS cannot read on its own.
 */
function onCardPointerMove(event: PointerEvent) {
  const card = event.currentTarget as HTMLElement
  const rect = card.getBoundingClientRect()
  card.style.setProperty('--vd-card-x', `${event.clientX - rect.left}px`)
  card.style.setProperty('--vd-card-y', `${event.clientY - rect.top}px`)
}

function onCardPointerLeave(event: PointerEvent) {
  const card = event.currentTarget as HTMLElement
  card.style.removeProperty('--vd-card-x')
  card.style.removeProperty('--vd-card-y')
}

/**
 * The accessibility band's evidence, as data: three measures and the command that produces the
 * first of them.
 */
const a11yStats = [
  { value: '0', label: 'home.a11yViolationsLabel', note: 'home.a11yViolationsNote' },
  { value: '4.5:1', label: 'home.a11yContrastLabel', note: 'home.a11yContrastNote' },
  { value: '3:1', label: 'home.a11yFocusLabel', note: 'home.a11yFocusNote' },
]

/** The four engines the library targets, with the version each is supported from. */
const browsers = [
  { name: 'Chrome', version: '134+', logo: chromeLogo },
  { name: 'Edge', version: '134+', logo: edgeLogo },
  { name: 'Safari', version: '26+', logo: safariLogo },
  { name: 'Firefox', version: '147+', logo: firefoxLogo },
]

/**
 * The three installation steps, shown in a mock editor window. `lang` doubles as the comment
 * syntax; `#` for a shell, `//` for TypeScript; so the prefix is derived once instead of being
 * written on each of the three.
 */
type Step = {
  value: string
  label: string
  body: string
  file?: string
  lang: string
  /**
   * Absent on the install step alone, whose command is not a constant: it is chosen from the
   * package manager the reader picked, so it is supplied at render time rather than written
   * here.
   */
  code?: string
}

const STEPS: Step[] = [
  {
    value: 'install',
    label: 'home.stepInstallLabel',
    body: 'home.stepInstallBody',
    file: undefined,
    lang: 'bash',
  },
  {
    value: 'styles',
    label: 'home.stepStylesLabel',
    body: 'home.stepStylesBody',
    file: 'main.ts',
    lang: 'ts',
    code: "import 'vectis-ui/styles.css'",
  },
  {
    value: 'use',
    label: 'home.stepUseLabel',
    body: 'home.stepUseBody',
    file: 'App.vue',
    lang: 'ts',
    code: "import { VButton } from 'vectis-ui'",
  },
]

/**
 * The four package managers and the one the command is shown in, both from the shared
 * composable: the installation page offers the same choice twice more, and a reader who has
 * picked theirs on one of the three should find it made on the others.
 */
const { managers, packageManager, commandFor } = usePackageManager()

/** Vue is a peer dependency here, where a Nuxt project gets it from the framework. */
const installCommand = computed(() => commandFor('vectis-ui vue'))

const installSteps = computed(() =>
  STEPS.map((step) => {
    const mark = step.lang === 'bash' ? '#' : '//'
    // The file name first, as a real file opens, then the sentence. `filter` is what lets the
    // first step have no file at all rather than an empty comment line.
    const header = [step.file, t(step.body)]
      .filter(Boolean)
      .map((line) => `${mark} ${line}`)
      .join('\n')

    // The install step is the one without a literal; see `code` on `Step`. `managed` carries
    // that same test to the template, so which step owns the toggle is decided here and once,
    // rather than by re-testing the step's id in the markup.
    return {
      ...step,
      label: t(step.label),
      managed: step.code === undefined,
      code: `${header}\n\n${step.code ?? installCommand.value}`,
    }
  }),
)

/** Which step is showing. */
const installStep = ref<string>(STEPS[0]!.value)
</script>

<template>
  <main class="vd-home">
    <div class="vd-limit vd-hero">
      <div>
        <!--
          The headline comes from the catalogue WITH its line break and its accent span: where a
          headline breaks is a decision about the sentence, and the two languages break in
          different places. The accent colour is applied from the scoped block through `:deep`,
          since content rendered as raw HTML carries no scope attribute of its own.
        -->
        <DocsProse tag="h1" keypath="home.heroTitle" variant="display" class="vd-hero-title" />
        <DocsProse keypath="home.heroBody" variant="body-xl" tone="muted" class="vd-hero-body" />
        <div class="vd-actions vd-hero-actions">
          <NuxtLink :to="docsHome" custom>
            <template #default="{ href, navigate }">
              <VButton
                variant="solid"
                tone="accent"
                size="lg"
                :icon-end="arrowRightAltIcon"
                :href="href ?? undefined"
                @click="navigate"
              >
                {{ t('home.heroCta') }}
              </VButton>
            </template>
          </NuxtLink>
        </div>
      </div>
    </div>

    <!--
      The section title is deliberately MONOCHROME. The accent span belongs to the hero headline
      alone, and repeating it down the page would spend the signal it carries.
    -->
    <section>
      <div class="vd-limit vd-band vd-centered">
        <VTypography variant="heading-1" as="h2" class="vd-stack-sm">
          {{ t('home.standardsHeading') }}
        </VTypography>
        <DocsProse
          keypath="home.standardsSubtitle"
          variant="body-lg"
          tone="muted"
          class="vd-measure vd-stack-lg"
        />
        <div class="vd-grid-3">
          <article
            v-for="card in cards"
            :key="card.title"
            class="vd-home-card"
            :data-accent="card.accent"
            @pointermove="onCardPointerMove"
            @pointerleave="onCardPointerLeave"
          >
            <VIcon :name="card.icon" :size="32" class="vd-card-icon" />
            <VTypography variant="heading-3" as="h3" class="vd-stack-sm">
              {{ t(card.title) }}
            </VTypography>
            <DocsProse :keypath="card.body" variant="body-md" tone="muted" />
          </article>
        </div>
      </div>
    </section>

    <section class="vd-limit vd-band vd-centered">
      <VTypography variant="heading-1" as="h2" class="vd-stack-sm">
        {{ t('home.accessibilityHeading') }}
      </VTypography>
      <DocsProse
        keypath="home.accessibilitySubtitle"
        variant="body-lg"
        tone="muted"
        class="vd-measure vd-stack-lg"
      />
      <!--
        Evidence rather than claims: three measures, and nothing arguing for them. What this
        band can say that no other design system's landing page can is that its accessibility is
        CHECKED and that the check BLOCKS; the figures are that check's output, so they carry
        the argument on their own and a sentence restating it would only soften it.
      -->
      <ul class="vd-proof">
        <li v-for="stat in a11yStats" :key="stat.label">
          <!--
            The figure is `as="p"`: the page's heading hierarchy belongs to the section, and a
            measure is not a heading. `display` supplies the size, nothing else does.
          -->
          <VTypography variant="display" as="p" class="vd-proof-figure">
            {{ stat.value }}
          </VTypography>
          <VTypography variant="label" as="p">{{ t(stat.label) }}</VTypography>
          <VTypography variant="caption" as="p" tone="muted">{{ t(stat.note) }}</VTypography>
        </li>
      </ul>
      <!-- A list because it is an enumeration, and the version reads as the logo's caption. -->
      <ul class="vd-browsers">
        <li v-for="browser in browsers" :key="browser.name">
          <img :src="browser.logo" :alt="browser.name" width="40" height="40" />
          <VChip size="xs" tone="neutral">{{ browser.version }}</VChip>
        </li>
      </ul>
    </section>

    <section class="vd-limit vd-band vd-centered">
      <VTypography variant="heading-1" as="h2" class="vd-stack-sm">
        {{ t('home.installHeading') }}
      </VTypography>
      <DocsProse
        keypath="home.installSubtitle"
        variant="body-lg"
        tone="muted"
        class="vd-measure vd-stack-lg"
      />
      <!--
        `align="center"` keeps the tabs at their own width, centred; and the rule still runs the
        full width, because the VTabs variant draws it on the BAR while `align` only centres the
        list sitting on it. `full-width` would be the opposite request: it makes the three tabs
        share the bar in equal parts.
      -->
      <div class="vd-editor">
        <VTabs
          v-model="installStep"
          variant="flat"
          align="center"
          :label="t('home.installTabsLabel')"
        >
          <VTab
            v-for="step in installSteps"
            :key="step.value"
            :value="step.value"
            :label="step.label"
          />
          <template #panels>
            <VTabPanel v-for="step in installSteps" :key="step.value" :value="step.value">
              <DocsCode :lang="step.lang" :code="step.code">
                <!--
                  The toggle belongs to the install step alone; the other two import from the
                  package and name no manager. `size="xs"` against the header's `sm` copy button
                  is deliberate: four text segments in a title bar are chrome, and at `sm` the
                  row stops fitting a phone.
                -->
                <template v-if="step.managed" #head>
                  <VToggle
                    v-model="packageManager"
                    mandatory
                    item-variant="outline"
                    selected-variant="soft"
                    tone="accent"
                    size="xs"
                    :label="t('common.code.packageManager')"
                  >
                    <VToggleItem
                      v-for="manager in managers"
                      :key="manager.value"
                      :value="manager.value"
                    >
                      {{ manager.value }}
                    </VToggleItem>
                  </VToggle>
                </template>
              </DocsCode>
            </VTabPanel>
          </template>
        </VTabs>
      </div>
    </section>
  </main>
</template>

<style scoped>
/*
 * The hero's glow; two pools of colour drifting out of the top of the page, so the first screen
 * is not one flat fill from edge to edge, and is not standing still either. It lives here
 * rather than in docs-layout.css for the reason that file states about itself: a pseudo-element
 * and its keyframes belong to the one component that draws them, as the outline's link states
 * do.
 */
/*
 * Two rules for content the catalogue renders as raw HTML: it carries no scope attribute, so
 * `:deep` is what reaches it; a plain scoped selector matches nothing there, and fails
 * silently. The `<code>` run inside a sentence is the one piece of type on this page that
 * VTypography cannot carry, being inside an `innerHTML` rather than a slot.
 */
.vd-home :deep(.vd-hero-accent) {
  color: var(--vectis-color-accent);
}
.vd-home :deep(code) {
  font-family: var(--vectis-text-family-code);
  font-size: var(--vectis-text-code-size);
}

/*
 * The feature cards, written once because the six are a loop. three LAYERS, and the order of
 * the two written here is the whole of the effect.
 */
.vd-home-card {
  /*
   * The wash and the hairline are tuned apart because they answer to different things. The wash
   * is a tint on a surface with the card's own copy sitting on it, so it SWAPS DIRECTION
   * between the themes: over near-white it has to be darker than the paper to register at all,
   * over near-black lighter than it.
   */
  --vd-wash-l: 58%;
  --vd-wash-c: 0.15;
  --vd-wash-a: 0.13;
  --vd-line-l: 58%;
  --vd-line-c: 0.19;

  position: relative;
  padding: var(--vectis-space-6);
  border: 1px solid var(--vectis-color-border);
  border-radius: var(--vectis-radius-surface);
  background:
    radial-gradient(
      140% 110% at 0% 0%,
      oklch(var(--vd-wash-l) var(--vd-wash-c) var(--vd-card-hue) / var(--vd-wash-a)),
      transparent 62%
    ),
    color-mix(in oklch, var(--vectis-color-surface-raised) 72%, transparent);
}
[data-theme='dark'] .vd-home-card {
  --vd-wash-l: 68%;
  --vd-wash-c: 0.17;
  --vd-wash-a: 0.18;
  --vd-line-l: 70%;
  --vd-line-c: 0.2;
}

/*
 * Keep hue variables unitless: relative-colour calc expressions accept numeric degrees but not
 * angle units.
 */
.vd-home-card[data-accent='orange'] {
  --vd-card-hue: 40;
}
.vd-home-card[data-accent='yellow'] {
  --vd-card-hue: 85;
}
.vd-home-card[data-accent='green'] {
  --vd-card-hue: 150;
}
.vd-home-card[data-accent='blue'] {
  --vd-card-hue: 255;
}
.vd-home-card[data-accent='violet'] {
  --vd-card-hue: 293;
}
.vd-home-card[data-accent='pink'] {
  --vd-card-hue: 350;
}

/*
 * The icon is MONOCHROME, and it is the page's own text colour rather than a black or a white:
 * `--vectis-color-text` is gray-900 in light and gray-50 in dark, which is the near-black and
 * the near-white this site is already set in. A pure #000/#fff pair would be the only two
 * absolute values on the page and would read as harder than everything around them.
 */
.vd-card-icon {
  display: block;
  margin: 0 auto var(--vectis-space-4);
  color: var(--vectis-color-text);
}

/*
 * `inherit` on the radius is load-bearing. A ring drawn at a different radius from the box it
 * hugs separates from the corners, and nothing in the console says so.
 */
@media (hover: hover) {
  .vd-home-card::before {
    content: '';
    position: absolute;
    inset: 0;
    padding: 1px;
    border-radius: inherit;
    background: radial-gradient(
      16rem circle at var(--vd-card-x, 50%) var(--vd-card-y, 50%),
      oklch(var(--vd-line-l) var(--vd-line-c) var(--vd-card-hue)),
      transparent 70%
    );
    mask:
      linear-gradient(black, black) content-box,
      linear-gradient(black, black);
    mask-composite: exclude;
    opacity: 0;
    transition: opacity var(--vectis-duration-base) var(--vectis-ease-out);
    pointer-events: none;
  }
  .vd-home-card:hover::before {
    opacity: 1;
  }

  /* The fade goes, the tracking stays: a glow that interpolated towards the pointer would not
     follow it, it would chase it. */
  @media (prefers-reduced-motion: reduce) {
    .vd-home-card::before {
      transition: none;
    }
  }
}

.vd-home {
  position: relative;
  /*
   * The stacking context is what confines that -1: without it the glow would slide behind
   * .vd-shell's own background and simply not appear, with nothing in the console to say why.
   */
  isolation: isolate;

  /*
   * The axis matters, in both directions. The pools sit on negative inline insets and drift
   * further sideways still, and overflow past the END of the line is what mints a horizontal
   * scrollbar on the whole document.
   */
  overflow-x: clip;

  /*
   * Use theme-specific glow intensity because identical translucent colours have different
   * visible strength on light and dark surfaces.
   */
  --vd-glow-l: 56%;
  --vd-glow-c: 0.26;
  --vd-glow-a1: 0.34;
  --vd-glow-a2: 0.26;
}
[data-theme='dark'] .vd-home {
  --vd-glow-l: 66%;
  --vd-glow-c: 0.27;
  --vd-glow-a1: 0.42;
  --vd-glow-a2: 0.32;
}
/*
 * What the two pools share. Sizes and colours are per-pool below, and so is every animation
 * NAME and DURATION; only the shape of the motion is common.
 */
.vd-home::before,
.vd-home::after {
  content: '';
  position: absolute;
  z-index: -1;
  pointer-events: none;
  /*
   * Each pool fades to nothing well inside its own box, in every direction; which makes it safe
   * to move. Nothing here has an edge to reveal.
   */
  background: radial-gradient(closest-side, var(--vd-pool), transparent);
  /*
   * The drift is `linear` and must stay so. Eased, a pool accelerates out of every keyframe and
   * coasts into the next; the same journey read as fast, slow, fast, which a wandering glow
   * must never do.
   */
  animation-timing-function: linear, var(--vectis-ease-in-out), var(--vectis-ease-in-out);
  animation-iteration-count: infinite;
}

/*
 * Use percentages for inline glow measurements to exclude scrollbar width; block measurements
 * use viewport height because the page height varies.
 */
.vd-home::before {
  --vd-pool: oklch(
    from var(--vectis-color-accent) var(--vd-glow-l) var(--vd-glow-c) h / var(--vd-glow-a1)
  );
  inset-block-start: calc(-1 * var(--vd-header-h) - 34vh);
  inset-inline-start: -20%;
  inline-size: 90%;
  block-size: 70vh;
  animation-name: vd-glow-drift-a, vd-glow-swell-a, vd-glow-pulse-a;
  animation-duration: 15s, 11s, 8s;
}
.vd-home::after {
  --vd-pool: oklch(
    from var(--vectis-color-accent) var(--vd-glow-l) var(--vd-glow-c) calc(h + 45) /
      var(--vd-glow-a2)
  );
  inset-block-start: calc(-1 * var(--vd-header-h) - 26vh);
  inset-inline-end: -14%;
  inline-size: 80%;
  block-size: 62vh;
  animation-name: vd-glow-drift-b, vd-glow-swell-b, vd-glow-pulse-b;
  animation-duration: 11s, 9s, 7s;
  /* Negative, so the page does not open on both pools sitting at their own 0% at once. */
  animation-delay:
    -7s,
    -3s,
    -4s;
}

/*
 * 0% and 100% must stay IDENTICAL in all six. That equality is the whole of the seamless loop:
 * an iteration ends exactly where the next one starts, so there is no frame at which the pool
 * jumps back.
 */
@keyframes vd-glow-drift-a {
  0%,
  100% {
    translate: 0 0;
  }
  12.5% {
    translate: 8% 4%;
  }
  25% {
    translate: 9% 13%;
  }
  37.5% {
    translate: 3% 19%;
  }
  50% {
    translate: -1% 27%;
  }
  62.5% {
    translate: -9% 24%;
  }
  75% {
    translate: -10% 15%;
  }
  87.5% {
    translate: -5% 7%;
  }
}
@keyframes vd-glow-drift-b {
  0%,
  100% {
    translate: 0 0;
  }
  12.5% {
    translate: -7% 4%;
  }
  25% {
    translate: -12% 10%;
  }
  37.5% {
    translate: -12% 18%;
  }
  50% {
    translate: -6% 22%;
  }
  62.5% {
    translate: 1% 21%;
  }
  75% {
    translate: 7% 15%;
  }
  87.5% {
    translate: 5% 6%;
  }
}

/* The swell is the pool's own breath, and it is the one place easing belongs: nothing crosses
   the screen, so there is no rate for a reader to read as uneven. */
@keyframes vd-glow-swell-a {
  0%,
  100% {
    scale: 1;
  }
  35% {
    scale: 1.09;
  }
  70% {
    scale: 0.96;
  }
}
@keyframes vd-glow-swell-b {
  0%,
  100% {
    scale: 1.05;
  }
  40% {
    scale: 0.94;
  }
  75% {
    scale: 1.12;
  }
}

/*
 * The pulse multiplies the pool's own alpha rather than replacing it; `--vd-glow-a1`/ `-a2`
 * stay the theme's business, and 1 is the rest value, so a reader who has asked for less motion
 * sees the glow at exactly the strength the theme tuned.
 */
@keyframes vd-glow-pulse-a {
  0%,
  100% {
    opacity: 0.85;
  }
  40% {
    opacity: 1;
  }
  70% {
    opacity: 0.72;
  }
}
@keyframes vd-glow-pulse-b {
  0%,
  100% {
    opacity: 0.8;
  }
  35% {
    opacity: 0.74;
  }
  65% {
    opacity: 1;
  }
}

/*
 * The glow stays painted, it just stops moving. With no animation the pools fall back to their
 * own declarations; no translate, no scale, and a full opacity, so the strength a reader sees
 * is exactly the one the theme tuned in `--vd-glow-a1`/ `-a2`.
 */
@media (prefers-reduced-motion: reduce) {
  .vd-home::before,
  .vd-home::after {
    animation: none;
  }
}
</style>
