<script setup lang="ts">
/**
 * The home page, in four bands: what the library is, the six decisions that shape it, what it
 * guarantees on accessibility and which engines it runs on, and how to install it.
 *
 * Two of the bands are centred and one is not, deliberately — the accessibility band reads down
 * a column beside its accordion, where centring a bulleted argument would only make it harder to
 * follow.
 */
import { VButton, VChip, VIcon, VTab, VTabPanel, VTabs, VTypography } from '@vectis/ui'
import { arrow_right_alt as arrowRightAltIcon } from '@vectis/ui/icons'

import chromeLogo from '~/assets/img/chrome-browser-svg.svg'
import edgeLogo from '~/assets/img/edge-browser-svg.svg'
import firefoxLogo from '~/assets/img/firefox-browser-svg.svg'
import safariLogo from '~/assets/img/safari-browser-svg.svg'

const { t } = useI18n()
const localePath = useLocalePath()

useHead({ title: () => t('home.documentTitle') })

const docsHome = computed(() => localePath('/docs/installation'))

/**
 * The six feature cards, as data: two catalogue keys, an icon, and an accent.
 *
 * `accent` NAMES A HUE, and that is all it names. The six are a CSS table keyed on
 * `data-accent`, and each entry there writes exactly one OKLCH hue angle — lightness, chroma
 * and alpha are the THEME's, declared once for the whole set. That split is the point: the six
 * read at one strength, so no card can turn out louder than its neighbour, and the two paints
 * each one carries (a corner wash and a hover hairline) cannot drift apart either.
 *
 * They are deliberately NOT derived from the accent role, which is what they used to be. Six
 * rotations off a single hue follow a repointed accent everywhere, and half of them then land
 * on a colour nobody chose — the four this site never picked were the price of the two it did.
 * Six hues written down are six decisions, and they hold whatever the accent becomes.
 *
 * Each is chosen for what its card is about: energy is orange, the web platform is blue, the
 * custom properties are the site's own violet, the layers green, the icons pink.
 *
 * The icons come from the SITE's registry (`icons/icons.ts`, regenerated by
 * `pnpm --filter @vectis/docs icons`): none of the six is among the 34 the library ships, and
 * the resolver hands an unknown name back to that registry by answering `undefined`.
 */
const cards = [
  { title: 'home.nativeTitle', body: 'home.nativeBody', icon: 'bolt', accent: 'orange' },
  { title: 'home.standardTitle', body: 'home.standardBody', icon: 'public', accent: 'yellow' },
  {
    title: 'home.customizationTitle',
    body: 'home.customizationBody',
    icon: 'palette',
    accent: 'violet',
  },
  { title: 'home.overridesTitle', body: 'home.overridesBody', icon: 'layers', accent: 'green' },
  { title: 'home.ssrTitle', body: 'home.ssrBody', icon: 'dns', accent: 'blue' },
  { title: 'home.iconsTitle', body: 'home.iconsBody', icon: 'interests', accent: 'pink' },
]

/**
 * Where the hover glow sits, and the only JavaScript on this page: a pointer position is the
 * one thing CSS cannot read on its own.
 *
 * BOUND PER CARD, not delegated to the grid, and that is forced rather than chosen:
 * `pointerleave` does NOT bubble, so a listener on the container would only ever fire when the
 * pointer left the whole grid — the glow would keep its last position while crossing from one
 * card to its neighbour. Per card, `currentTarget` is always the card itself, which also
 * removes the `closest()` a delegated handler would have needed to turn an event fired on an
 * icon or a heading into the box it belongs to.
 *
 * The write goes through `setProperty` rather than a reactive `:style`, deliberately: a binding
 * would re-render the grid on every frame of a pointer move, for two decorative custom
 * properties nothing else reads.
 *
 * Clearing on leave is not tidiness. The glow is revealed by `:hover`, so leaving the values
 * behind would light it at the point the pointer LEFT for the frame or two before the first
 * move event of the next entry arrives.
 */
function onCardPointerMove(event: PointerEvent) {
  const card = event.currentTarget as HTMLElement
  const rect = card.getBoundingClientRect()
  card.style.setProperty('--vd-card-x', `${event.clientX - rect.left}px`)
  card.style.setProperty('--vd-card-y', `${event.clientY - rect.top}px`)
}

function onCardPointerLeave(event: PointerEvent) {
  const card = event.currentTarget as HTMLElement
  card.style.removeProperty('--vd-card-x')
  card.style.removeProperty('--vd-card-y')
}

/**
 * The accessibility band's evidence, as data: three measures and the command that produces the
 * first of them.
 *
 * `value` is a TEMPLATE CONSTANT and never a catalogue key. Each is made of digits and universal
 * punctuation, which is exactly what the dictionary boundary leaves outside — the rule VBadge's
 * `99+` and the `N/M` counter already follow. Only the words beneath them are translated.
 *
 * All three are chosen so that NOTHING HERE DRIFTS. A component count or a story count would be
 * out of date by the next commit and there is no gate that would say so; a conformance floor and
 * a violation count that CI enforces on every push are true for as long as the workflow is. That
 * is the same standard `bench:size` sets for the figures the README publishes.
 */
const a11yStats = [
  { value: '0', label: 'home.a11yViolationsLabel', note: 'home.a11yViolationsNote' },
  { value: '4.5:1', label: 'home.a11yContrastLabel', note: 'home.a11yContrastNote' },
  { value: '3:1', label: 'home.a11yFocusLabel', note: 'home.a11yFocusNote' },
]

/**
 * The four engines the library targets, with the version each is supported from.
 *
 * Neither half belongs in the catalogue: a browser is a proper noun, and a version number is
 * made of digits — the two things the dictionary boundary deliberately leaves outside. The
 * figures are `cssTarget` in `packages/ui/vite.config.ts`, and they must be kept in step with it
 * by hand; there is no import that could cross a package boundary here.
 *
 * The logos are brand artwork, so they are `<img>` and not VIcon: VIcon paints a single path in
 * `currentcolor`, which is the whole of its contract and exactly wrong for a multicoloured mark.
 * Inlining them would also collide their gradient ids — Edge and Firefox both declare an `id="b"`
 * — where a separate document per file makes that impossible. `~/assets` is rewritten by Vite
 * with the site's base URL, so `/vectis-ui/` is written nowhere.
 *
 * `alt` carries the name because nothing else does: the logo IS the label here.
 */
const browsers = [
  { name: 'Chrome', version: '125+', logo: chromeLogo },
  { name: 'Edge', version: '125+', logo: edgeLogo },
  { name: 'Safari', version: '26+', logo: safariLogo },
  { name: 'Firefox', version: '147+', logo: firefoxLogo },
]

/**
 * The three installation steps, shown in a mock editor window.
 *
 * Each step's file name and its sentence of explanation live INSIDE the sample, as the comment
 * a real file opens with — which is why this is a computed rather than a constant: the sentence
 * comes from the catalogue, so the code string is localised. That is the one place on the site
 * where a sample is not English, and the departure is deliberate: the rule protects the agreement
 * between a LIVE demo and its printed snippet, and there is no demo here, so the comment is prose
 * and belongs in the reader's language.
 *
 * `lang` doubles as the comment syntax — `#` for a shell, `//` for TypeScript — so the prefix is
 * derived once instead of being written on each of the three. It stays a display label otherwise:
 * DocsCode does no highlighting, and `ts` matches the ten other samples on the site.
 *
 * `file` is a template constant and never a catalogue key: a file name is not translated.
 */
const STEPS = [
  {
    value: 'install',
    label: 'home.stepInstallLabel',
    body: 'home.stepInstallBody',
    file: undefined,
    lang: 'bash',
    code: 'pnpm add @vectis/ui vue',
  },
  {
    value: 'styles',
    label: 'home.stepStylesLabel',
    body: 'home.stepStylesBody',
    file: 'main.ts',
    lang: 'ts',
    code: "import '@vectis/ui/styles.css'",
  },
  {
    value: 'use',
    label: 'home.stepUseLabel',
    body: 'home.stepUseBody',
    file: 'App.vue',
    lang: 'ts',
    code: "import { VButton } from '@vectis/ui'",
  },
]

const installSteps = computed(() =>
  STEPS.map((step) => {
    const mark = step.lang === 'bash' ? '#' : '//'
    // The file name first, as a real file opens, then the sentence. `filter` is what lets the
    // first step have no file at all rather than an empty comment line.
    const header = [step.file, t(step.body)]
      .filter(Boolean)
      .map((line) => `${mark} ${line}`)
      .join('\n')

    return { ...step, label: t(step.label), code: `${header}\n\n${step.code}` }
  }),
)

/**
 * Which step is showing. It must name an existing tab at all times: VTabs hands `tabindex="0"`
 * to the selected one and to no other, so a value matching nothing would leave the whole bar
 * unreachable from the keyboard.
 */
const installStep = ref<string>(STEPS[0]!.value)
</script>

<template>
  <main class="vd-home">
    <div class="vd-limit vd-hero">
      <div>
        <!--
          The headline comes from the catalogue WITH its line break and its accent span: where a
          headline breaks is a decision about the sentence, and the two languages break in
          different places. The accent colour is applied from the scoped block through `:deep`,
          since content rendered as raw HTML carries no scope attribute of its own.
        -->
        <DocsProse tag="h1" keypath="home.heroTitle" variant="display" class="vd-hero-title" />
        <DocsProse keypath="home.heroBody" variant="body-xl" tone="muted" class="vd-hero-body" />
        <div class="vd-actions vd-hero-actions">
          <NuxtLink :to="docsHome" custom>
            <template #default="{ href, navigate }">
              <VButton
                variant="solid"
                tone="accent"
                size="lg"
                :icon-end="arrowRightAltIcon"
                :href="href ?? undefined"
                @click="navigate"
              >
                {{ t('home.heroCta') }}
              </VButton>
            </template>
          </NuxtLink>
        </div>
      </div>
    </div>

    <!--
      The section title is deliberately MONOCHROME. The accent span belongs to the hero headline
      alone, and repeating it down the page would spend the signal it carries.
    -->
    <section>
      <div class="vd-limit vd-band vd-centered">
        <VTypography variant="heading-1" as="h2" class="vd-stack-sm">
          {{ t('home.standardsHeading') }}
        </VTypography>
        <DocsProse
          keypath="home.standardsSubtitle"
          variant="body-lg"
          tone="muted"
          class="vd-measure vd-stack-lg"
        />
        <div class="vd-grid-3">
          <article
            v-for="card in cards"
            :key="card.title"
            class="vd-home-card"
            :data-accent="card.accent"
            @pointermove="onCardPointerMove"
            @pointerleave="onCardPointerLeave"
          >
            <!-- Decorative: the heading beneath it carries the meaning, so VIcon gets no label. -->
            <VIcon :name="card.icon" :size="32" class="vd-card-icon" />
            <VTypography variant="heading-3" as="h3" class="vd-stack-sm">
              {{ t(card.title) }}
            </VTypography>
            <DocsProse :keypath="card.body" variant="body-md" tone="muted" />
          </article>
        </div>
      </div>
    </section>

    <!--
      Deliberately NOT centred, unlike the band above: the text is read down a column, aligned
      to the start of the grid, with the accordion beside it.
    -->
    <section class="vd-limit vd-band">
      <div class="vd-split">
        <div class="vd-split-prose">
          <VTypography variant="heading-1" as="h2" class="vd-stack-sm">
            {{ t('home.accessibilityHeading') }}
          </VTypography>
          <DocsProse
            keypath="home.accessibilitySubtitle"
            variant="body-lg"
            tone="muted"
            class="vd-stack-lg"
          />
          <!-- A list because it is an enumeration, and the version reads as the logo's caption. -->
          <ul class="vd-browsers">
            <li v-for="browser in browsers" :key="browser.name">
              <img :src="browser.logo" :alt="browser.name" width="40" height="40" />
              <VChip size="xs" tone="neutral">{{ browser.version }}</VChip>
            </li>
          </ul>
        </div>
        <!--
          Evidence rather than claims: three measures, and nothing arguing for them. What this
          band can say that no other design system's landing page can is that its accessibility
          is CHECKED and that the check BLOCKS — the figures are that check's output, so they
          carry the argument on their own and a sentence restating it would only soften it.
        -->
        <ul class="vd-proof">
          <li v-for="stat in a11yStats" :key="stat.label">
            <!--
              The figure is `as="p"`: the page's heading hierarchy belongs to the section, and a
              measure is not a heading. `display` supplies the size, nothing else does.
            -->
            <VTypography variant="display" as="p" class="vd-proof-figure">
              {{ stat.value }}
            </VTypography>
            <VTypography variant="label" as="p">{{ t(stat.label) }}</VTypography>
            <VTypography variant="caption" as="p" tone="muted">{{ t(stat.note) }}</VTypography>
          </li>
        </ul>
      </div>
    </section>

    <section class="vd-limit vd-band vd-centered">
      <VTypography variant="heading-1" as="h2" class="vd-stack-sm">
        {{ t('home.installHeading') }}
      </VTypography>
      <DocsProse
        keypath="home.installSubtitle"
        variant="body-lg"
        tone="muted"
        class="vd-measure vd-stack-lg"
      />
      <!--
        The code block IS the window: DocsCode already carries a card, a title bar and the copy
        button, so `flat` leaves the tabs as a row over a rule and adds no second frame.

        `align="center"` keeps the tabs at their own width, centred — and the rule still runs the
        full width, because the VTabs variant draws it on the BAR while `align` only centres the
        list sitting on it. `grow` would be the opposite request: it makes the three tabs share
        the bar in equal parts.
      -->
      <div class="vd-editor">
        <VTabs
          v-model="installStep"
          variant="flat"
          align="center"
          :label="t('home.installTabsLabel')"
        >
          <VTab
            v-for="step in installSteps"
            :key="step.value"
            :value="step.value"
            :label="step.label"
          />
          <template #panels>
            <VTabPanel v-for="step in installSteps" :key="step.value" :value="step.value">
              <DocsCode :lang="step.lang" :code="step.code" />
            </VTabPanel>
          </template>
        </VTabs>
      </div>
    </section>
  </main>
</template>

<style scoped>
/*
 * The hero's glow — two pools of colour drifting out of the top of the page, so the first
 * screen is not one flat fill from edge to edge, and is not standing still either.
 *
 * It lives here rather than in docs-layout.css for the reason that file states about itself: a
 * pseudo-element and its keyframes belong to the one component that draws them, as the outline's
 * link states do. It hangs off <main>, which is a direct child of the flex column and so
 * spans the full width already — anchoring it on .vd-hero instead would stop the glow at the
 * 1440px content column and leave a vertical seam on a wider screen, and the usual
 * `calc(50% - 50vw)` bleed would then overflow by half a scrollbar.
 *
 * ONE POOL PER PSEUDO-ELEMENT, and that is the whole shape of the thing. The two pools used to
 * be two background layers on a single ::before, which is fine while nothing moves: the only
 * way to shift two layers of one background independently is `background-position`, and that
 * REPAINTS a full-width surface on every frame. Split across ::before and ::after, each pool
 * animates in `translate`, `scale` and `opacity` — the three properties the compositor takes
 * off the main thread, the argument VSkeletonLoader already writes for its wave.
 *
 * The split is also what removed the mask. Each pool is now a self-contained ellipse whose
 * gradient dies out in EVERY direction (`closest-side` … `transparent`), so there is no edge
 * anywhere for the movement to reveal. A masked full-width band would have shown its own top
 * edge the moment it drifted down, which is exactly what it is asked to do here.
 *
 * The colours are RELATIVE to the accent role (`oklch(from …)`, the VSkeletonLoader idiom):
 * this site repoints that role to violet, and the second pool sits 45 degrees round the hue
 * circle from wherever it lands. Repointing the accent repaints the glow, with no hue written
 * as a number and no second place to keep in step.
 */
/*
 * Two rules for content the catalogue renders as raw HTML: it carries no scope attribute, so
 * `:deep` is what reaches it — a plain scoped selector matches nothing there, and fails
 * silently. The `<code>` run inside a sentence is the one piece of type on this page that
 * VTypography cannot carry, being inside an `innerHTML` rather than a slot.
 */
.vd-home :deep(.vd-hero-accent) {
  color: var(--vectis-color-accent);
}
.vd-home :deep(code) {
  font-family: var(--vectis-text-family-code);
  font-size: var(--vectis-text-code-size);
}

/*
 * The feature cards, written once because the six are a loop.
 *
 * THREE LAYERS, and the order of the two written here is the whole of the effect. On top, a
 * wash of the card's own hue thrown from the TOP-LEFT corner and gone by the middle of the box;
 * under it, the raised surface. A background colour is always the BOTTOM layer of a `background`
 * shorthand whatever its position in the list, so the two cannot be written the other way round
 * by accident. The third layer is the ::before hairline further down, which is the same hue
 * again at hover strength.
 *
 * The surface is a MIX towards transparent rather than the flat raised token — the header bar's
 * idiom — which is what lets the hero's glow wash under the top row instead of stopping at it.
 * Both themes take the same recipe: `surface-raised` already flips, so the card is a shade above
 * the page in light and a shade above the near-black in dark, with one declaration. The wash is
 * translucent for the same reason, so it tints what passes through rather than shutting it out.
 *
 * The wash is an ELLIPSE `at 0% 0%` and not a linear gradient down the diagonal: a linear one
 * has a direction but no origin, so its colour would run the full length of the top-right and
 * bottom-left edges instead of pooling in the one corner. `140% 110%` is measured against the
 * card's own box, so a tall card and a short one hold the same shape of pool.
 */
.vd-home-card {
  /*
   * What a hue is worth, and the only place the six colours are given a strength. Dark restates
   * all five in the rule immediately below; there is no third theme.
   *
   * The wash and the hairline are tuned apart because they answer to different things. The wash
   * is a tint on a surface with the card's own copy sitting on it, so it SWAPS DIRECTION between
   * the themes: over near-white it has to be darker than the paper to register at all, over
   * near-black lighter than it. The hairline has nothing reading through it, so it takes the
   * vivid end of the same hue and only rises in dark, where a mid-lightness stroke would sink
   * into the border it is replacing.
   *
   * The alpha is the HIGHER of the two in dark, which reads backwards and is not: what limits it
   * is the muted body text that sits on the corner, and dark starts that pairing near 10:1 where
   * light starts it near 7:1. The tint costs almost nothing at either end — the corner measures
   * 9.6:1 in dark and 6.4:1 in light at the values below, so both stay clear of AA — but light
   * is the theme with less to spend, and it is the one to re-measure if this table moves.
   */
  --vd-wash-l: 58%;
  --vd-wash-c: 0.15;
  --vd-wash-a: 0.13;
  --vd-line-l: 58%;
  --vd-line-c: 0.19;

  position: relative;
  padding: var(--vectis-space-6);
  border: 1px solid var(--vectis-color-border);
  border-radius: var(--vectis-radius-surface);
  background:
    radial-gradient(
      140% 110% at 0% 0%,
      oklch(var(--vd-wash-l) var(--vd-wash-c) var(--vd-card-hue) / var(--vd-wash-a)),
      transparent 62%
    ),
    color-mix(in oklch, var(--vectis-color-surface-raised) 72%, transparent);
}
[data-theme='dark'] .vd-home-card {
  --vd-wash-l: 68%;
  --vd-wash-c: 0.17;
  --vd-wash-a: 0.18;
  --vd-line-l: 70%;
  --vd-line-c: 0.2;
}

/*
 * The six accents, as a table of HUES and nothing else.
 *
 * One number per card: an OKLCH hue angle, chosen for the subject rather than derived from
 * anything. The lightness, chroma and alpha that turn a hue into the two paints — the corner
 * wash and the hover hairline — are the THEME's: the five properties on `.vd-home-card` itself,
 * restated by the dark rule beside it. That is what keeps the six at one strength — a card can
 * differ from its neighbours in hue and in nothing else, so none of them can come out shouting.
 *
 * The values sit where a muted version of each colour lives on the OKLCH wheel: 40 red-orange,
 * 85 yellow, 150 green, 255 blue, 293 the site's own violet, 350 pink. They are spread widely
 * enough that no two neighbours in the grid read as the same wash.
 *
 * TRAP — these are UNITLESS, and they must stay so. They are substituted into `oklch()` as the
 * `<hue>` argument, where a number is read as degrees; writing `40deg` would be valid there but
 * NOT inside the `calc()` of a relative colour, which is the form the hero glow below uses — so
 * the two would part company the day one of these hues was reused there. An invalid channel
 * takes down the whole declaration holding it, in silence and with nothing in the console.
 */
.vd-home-card[data-accent='orange'] {
  --vd-card-hue: 40;
}
.vd-home-card[data-accent='yellow'] {
  --vd-card-hue: 85;
}
.vd-home-card[data-accent='green'] {
  --vd-card-hue: 150;
}
.vd-home-card[data-accent='blue'] {
  --vd-card-hue: 255;
}
.vd-home-card[data-accent='violet'] {
  --vd-card-hue: 293;
}
.vd-home-card[data-accent='pink'] {
  --vd-card-hue: 350;
}

/*
 * The icon is MONOCHROME, and it is the page's own text colour rather than a black or a white:
 * `--vectis-color-text` is gray-900 in light and gray-50 in dark, which is the near-black and
 * the near-white this site is already set in. A pure #000/#fff pair would be the only two
 * absolute values on the page and would read as harder than everything around them.
 *
 * The colour on these cards is the wash and the hover hairline; six tinted glyphs on top of it
 * was one signal too many, and the tint is the quieter half.
 */
.vd-card-icon {
  display: block;
  margin: 0 auto var(--vectis-space-4);
  color: var(--vectis-color-text);
}

/*
 * The glow that follows the pointer along the card's border.
 *
 * The ring is a `::before` inset to the card's own box, filled with a radial gradient centred on
 * the two custom properties the page's pointer handler writes, then CUT DOWN TO ITS BORDER by
 * two masks composited with `exclude`: one clipped to the content box, one to the border box, so
 * what survives is the `padding` band between them. That is the standard border-gradient trick,
 * and the 1px padding is what makes the band a hairline.
 *
 * TRAP — `inherit` on the radius is load-bearing. A ring drawn at a different radius from the
 * box it hugs separates from the corners, and nothing in the console says so.
 *
 * Behind `hover: hover` and never `any-hover`, which is true as soon as ANY hovering pointer is
 * attached: on a touch screen the glow would light where the last tap landed and stay there.
 */
@media (hover: hover) {
  .vd-home-card::before {
    content: '';
    position: absolute;
    inset: 0;
    padding: 1px;
    border-radius: inherit;
    background: radial-gradient(
      16rem circle at var(--vd-card-x, 50%) var(--vd-card-y, 50%),
      oklch(var(--vd-line-l) var(--vd-line-c) var(--vd-card-hue)),
      transparent 70%
    );
    mask:
      linear-gradient(black, black) content-box,
      linear-gradient(black, black);
    mask-composite: exclude;
    opacity: 0;
    transition: opacity var(--vectis-duration-base) var(--vectis-ease-out);
    pointer-events: none;
  }
  .vd-home-card:hover::before {
    opacity: 1;
  }

  /* The fade goes, the tracking stays: a glow that interpolated towards the pointer would not
     follow it, it would chase it. */
  @media (prefers-reduced-motion: reduce) {
    .vd-home-card::before {
      transition: none;
    }
  }
}

.vd-home {
  position: relative;
  /*
   * The glow paints at z-index -1 — above the shell's flat background, below the copy, so no
   * text contrast is measured against it. The stacking context is what confines that -1:
   * without it the glow would slide behind .vd-shell's own background and simply not appear,
   * with nothing in the console to say why.
   */
  isolation: isolate;

  /*
   * TRAP — the axis matters, in both directions. The pools sit on negative inline insets and
   * drift further sideways still, and overflow past the END of the line is what mints a
   * horizontal scrollbar on the whole document. `clip` on the inline axis alone is the fix:
   * `clip` is the ONE value that may pair with `visible` (any other would force the other axis
   * to `auto`), so the box does not become a scroll container, and the block axis stays
   * unclipped — which is what preserves the pools' bleed ABOVE this element, the whole reason
   * the glow shows through the header. Written `overflow: clip`, it would cut the glow off flat
   * under the bar.
   */
  overflow-x: clip;

  /*
   * The pools' INTENSITY is the one thing the theme owns, and it has to: the recipe below
   * replaces the accent's lightness and chroma outright, so both themes paint the same ink —
   * what changes is the paper. The same translucent violet that reads clearly over a near
   * black surface barely tints a white one, so light takes a darker, more saturated pool to
   * arrive at the same visible strength, and dark takes a brighter one it can afford. Only
   * the hue is still read off the accent, which is what keeps a repointed accent repainting
   * the glow with no number written twice.
   */
  --vd-glow-l: 56%;
  --vd-glow-c: 0.26;
  --vd-glow-a1: 0.34;
  --vd-glow-a2: 0.26;
}
[data-theme='dark'] .vd-home {
  --vd-glow-l: 66%;
  --vd-glow-c: 0.27;
  --vd-glow-a1: 0.42;
  --vd-glow-a2: 0.32;
}
/*
 * What the two pools share. Sizes and colours are per-pool below, and so is every animation
 * NAME and DURATION — only the shape of the motion is common.
 *
 * `--vectis-ease-in-out` is the token whose own description names looping animations that cross
 * a track: symmetric, so the pool eases out of one keyframe and into the next at the same rate,
 * which reads as a breath rather than a shuttle.
 *
 * No `will-change`. An element with a running `translate`/`scale`/`opacity` animation is already
 * promoted to its own layer by the engine; declaring it permanently would hold that memory for
 * two surfaces this size and buy nothing.
 */
.vd-home::before,
.vd-home::after {
  content: '';
  position: absolute;
  z-index: -1;
  pointer-events: none;
  /* Each pool fades to nothing well inside its own box, in every direction — which is what
     makes it safe to move. Nothing here has an edge to reveal. */
  background: radial-gradient(closest-side, var(--vd-pool), transparent);
  /*
   * Positional, and it lines up with the `animation-name` list each pool declares below: DRIFT,
   * then swell, then pulse. Both pools order them the same way, which is what lets the list be
   * written once here instead of twice down there.
   *
   * The drift is `linear` and must stay so. Eased, a pool accelerates out of every keyframe and
   * coasts into the next — the same journey read as fast, slow, fast, which is what a wandering
   * glow must never do. A constant rate over eight roughly equal legs is what makes the path
   * continuous instead. Easing is right for the other two, where nothing travels: swelling and
   * brightening are supposed to breathe.
   */
  animation-timing-function: linear, var(--vectis-ease-in-out), var(--vectis-ease-in-out);
  animation-iteration-count: infinite;
}

/*
 * Two off-centre pools rather than one centred: a single one reads as a vignette, and this pair
 * leaves the middle of the headline on the flat surface. They overlap across the top of the
 * screen, which is what gives the header bar a colour of its own instead of a gradient with a
 * visible seam between two circles.
 *
 * Both are pulled up past the header's own height, so the colour starts at the very top of the
 * page rather than under the bar. That is only worth anything because the header's background
 * is a translucent mix rather than the flat surface — see DocsHeader.vue, where the two halves
 * of this effect meet.
 *
 * The inline measurements are percentages (of .vd-home, so exact) and not `vw`, which counts
 * the scrollbar; the block ones stay in `vh`, since .vd-home is as tall as the whole page and a
 * percentage of it would mean nothing. The insets are chosen so each ellipse's CENTRE lands
 * where its pool used to be: 25% and 74% across, both a hair below the top of the viewport.
 */
.vd-home::before {
  --vd-pool: oklch(
    from var(--vectis-color-accent) var(--vd-glow-l) var(--vd-glow-c) h / var(--vd-glow-a1)
  );
  inset-block-start: calc(-1 * var(--vd-header-h) - 34vh);
  inset-inline-start: -20%;
  inline-size: 90%;
  block-size: 70vh;
  animation-name: vd-glow-drift-a, vd-glow-swell-a, vd-glow-pulse-a;
  animation-duration: 15s, 11s, 8s;
}
.vd-home::after {
  --vd-pool: oklch(
    from var(--vectis-color-accent) var(--vd-glow-l) var(--vd-glow-c) calc(h + 45) /
      var(--vd-glow-a2)
  );
  inset-block-start: calc(-1 * var(--vd-header-h) - 26vh);
  inset-inline-end: -14%;
  inline-size: 80%;
  block-size: 62vh;
  animation-name: vd-glow-drift-b, vd-glow-swell-b, vd-glow-pulse-b;
  animation-duration: 11s, 9s, 7s;
  /* Negative, so the page does not open on both pools sitting at their own 0% at once. */
  animation-delay:
    -7s,
    -3s,
    -4s;
}

/*
 * TRAP — 0% and 100% must stay IDENTICAL in all six. That equality is the whole of the seamless
 * loop: an iteration ends exactly where the next one starts, so there is no frame at which the
 * pool jumps back. Change one end without the other and the glow snaps, once per period, at a
 * distance no easing can hide.
 *
 * Travel, size and intensity are three separate animations on purpose. They touch disjoint
 * properties — `translate`, `scale`, `opacity` — so they compose rather than fight, and each
 * pool's three periods are coprime (15/11/8 and 11/9/7 seconds), which is what stops them from
 * re-syncing into a recognisable beat. One animation per pool would replay the same gesture on
 * the dot every 15 seconds, and it would also force the travel to share the breath's easing.
 *
 * TRAP — the eight legs of a drift must stay ROUGHLY EQUAL IN LENGTH, since `linear` divides
 * the time between them equally. A leg twice its neighbour's length is travelled at twice the
 * speed, which brings back by the back door exactly the fast/slow reading the linear rate was
 * chosen to remove. Both paths below hold to within about 5%.
 *
 * A `translate` percentage resolves against the element's OWN box, so the 27% below is 27% of
 * 70vh — close to 19vh of travel down over the hero, which is where the glow is meant to reach.
 */
@keyframes vd-glow-drift-a {
  0%,
  100% {
    translate: 0 0;
  }
  12.5% {
    translate: 8% 4%;
  }
  25% {
    translate: 9% 13%;
  }
  37.5% {
    translate: 3% 19%;
  }
  50% {
    translate: -1% 27%;
  }
  62.5% {
    translate: -9% 24%;
  }
  75% {
    translate: -10% 15%;
  }
  87.5% {
    translate: -5% 7%;
  }
}
@keyframes vd-glow-drift-b {
  0%,
  100% {
    translate: 0 0;
  }
  12.5% {
    translate: -7% 4%;
  }
  25% {
    translate: -12% 10%;
  }
  37.5% {
    translate: -12% 18%;
  }
  50% {
    translate: -6% 22%;
  }
  62.5% {
    translate: 1% 21%;
  }
  75% {
    translate: 7% 15%;
  }
  87.5% {
    translate: 5% 6%;
  }
}

/* The swell is the pool's own breath, and it is the one place easing belongs: nothing crosses
   the screen, so there is no rate for a reader to read as uneven. */
@keyframes vd-glow-swell-a {
  0%,
  100% {
    scale: 1;
  }
  35% {
    scale: 1.09;
  }
  70% {
    scale: 0.96;
  }
}
@keyframes vd-glow-swell-b {
  0%,
  100% {
    scale: 1.05;
  }
  40% {
    scale: 0.94;
  }
  75% {
    scale: 1.12;
  }
}

/*
 * The pulse multiplies the pool's own alpha rather than replacing it — `--vd-glow-a1`/`-a2` stay
 * the theme's business, and 1 is the rest value, so a reader who has asked for less motion sees
 * the glow at exactly the strength the theme tuned.
 */
@keyframes vd-glow-pulse-a {
  0%,
  100% {
    opacity: 0.85;
  }
  40% {
    opacity: 1;
  }
  70% {
    opacity: 0.72;
  }
}
@keyframes vd-glow-pulse-b {
  0%,
  100% {
    opacity: 0.8;
  }
  35% {
    opacity: 0.74;
  }
  65% {
    opacity: 1;
  }
}

/* The glow stays painted, it just stops moving. With no animation the pools fall back to their
   own declarations — no translate, no scale, and a full opacity, so the strength a reader sees
   is exactly the one the theme tuned in `--vd-glow-a1`/`-a2`. */
@media (prefers-reduced-motion: reduce) {
  .vd-home::before,
  .vd-home::after {
    animation: none;
  }
}
</style>
