/**
 * The design system's icon names, and what each icon library calls the same drawing. Every
 * name below was checked against the published name list of the library version the builder
 * targets: @lucide/vue 1.52, @heroicons/vue 2.2 (24px outline), @phosphor-icons/web 2.1,
 * @tabler/icons-webfont 3.49, remixicon 4.9 (both `-line` and `-fill` exist),
 * Font Awesome Free 7.3 (solid) and bootstrap-icons 1.13.
 */

/** The names VIcon draws itself: the contract a consumer's resolver has to cover. */
export const BUILTIN_ICON_NAMES = [
  'add',
  'arrow_downward',
  'arrow_downward_alt',
  'arrow_drop_down',
  'arrow_drop_up',
  'arrow_left_alt',
  'arrow_right_alt',
  'arrow_upward',
  'arrow_upward_alt',
  'attach_file',
  'audio_file',
  'calendar_today',
  'check',
  'check_circle',
  'chevron_left',
  'chevron_right',
  'close',
  'cloud_upload',
  'code',
  'colorize',
  'description',
  'error',
  'expand_less',
  'expand_more',
  'first_page',
  'folder_zip',
  'image',
  'inbox',
  'info',
  'last_page',
  'more_horiz',
  'notifications',
  'open_in_new',
  'picture_as_pdf',
  'priority_high',
  'remove',
  'schedule',
  'search',
  'search_off',
  'star',
  'swap_vert',
  'table_chart',
  'video_file',
  'warning',
] as const

/** The further names the preview uses, mapped so that every library draws the whole page. */
export const PREVIEW_ICON_NAMES = [
  'home',
  'settings',
  'person',
  'group',
  'folder',
  'mail',
  'edit',
  'delete',
  'download',
  'logout',
  'bar_chart',
  'dashboard',
  'favorite',
] as const

export type AliasedIconName =
  (typeof BUILTIN_ICON_NAMES)[number] | (typeof PREVIEW_ICON_NAMES)[number]

/**
 * For the two component libraries, the value is the exported component's name; for the
 * webfonts, the icon's name inside its class (`ph-<name>`, `ti-<name>`, `ri-<name>-line`…).
 */
export const ICON_ALIASES = {
  lucide: {
    add: 'Plus',
    arrow_downward: 'ArrowDown',
    arrow_downward_alt: 'ArrowDown',
    arrow_drop_down: 'ChevronDown',
    arrow_drop_up: 'ChevronUp',
    arrow_left_alt: 'ArrowLeft',
    arrow_right_alt: 'ArrowRight',
    arrow_upward: 'ArrowUp',
    arrow_upward_alt: 'ArrowUp',
    attach_file: 'Paperclip',
    audio_file: 'FileMusic',
    calendar_today: 'Calendar',
    check: 'Check',
    check_circle: 'CircleCheck',
    chevron_left: 'ChevronLeft',
    chevron_right: 'ChevronRight',
    close: 'X',
    cloud_upload: 'CloudUpload',
    code: 'Code',
    colorize: 'Pipette',
    description: 'FileText',
    error: 'CircleAlert',
    expand_less: 'ChevronUp',
    expand_more: 'ChevronDown',
    first_page: 'ChevronFirst',
    folder_zip: 'FileArchive',
    image: 'Image',
    inbox: 'Inbox',
    info: 'Info',
    last_page: 'ChevronLast',
    more_horiz: 'Ellipsis',
    notifications: 'Bell',
    open_in_new: 'ExternalLink',
    picture_as_pdf: 'FileType',
    priority_high: 'CircleAlert',
    remove: 'Minus',
    schedule: 'Clock',
    search: 'Search',
    search_off: 'SearchX',
    star: 'Star',
    swap_vert: 'ArrowUpDown',
    table_chart: 'Table',
    video_file: 'FileVideoCamera',
    warning: 'TriangleAlert',
    home: 'House',
    settings: 'Settings',
    person: 'User',
    group: 'Users',
    folder: 'Folder',
    mail: 'Mail',
    edit: 'Pencil',
    delete: 'Trash',
    download: 'Download',
    logout: 'LogOut',
    bar_chart: 'ChartColumn',
    dashboard: 'LayoutDashboard',
    favorite: 'Heart',
  },
  heroicons: {
    add: 'PlusIcon',
    arrow_downward: 'ArrowDownIcon',
    arrow_downward_alt: 'ArrowDownIcon',
    arrow_drop_down: 'ChevronDownIcon',
    arrow_drop_up: 'ChevronUpIcon',
    arrow_left_alt: 'ArrowLeftIcon',
    arrow_right_alt: 'ArrowRightIcon',
    arrow_upward: 'ArrowUpIcon',
    arrow_upward_alt: 'ArrowUpIcon',
    attach_file: 'PaperClipIcon',
    audio_file: 'MusicalNoteIcon',
    calendar_today: 'CalendarIcon',
    check: 'CheckIcon',
    check_circle: 'CheckCircleIcon',
    chevron_left: 'ChevronLeftIcon',
    chevron_right: 'ChevronRightIcon',
    close: 'XMarkIcon',
    cloud_upload: 'CloudArrowUpIcon',
    code: 'CodeBracketIcon',
    colorize: 'EyeDropperIcon',
    description: 'DocumentTextIcon',
    error: 'ExclamationCircleIcon',
    expand_less: 'ChevronUpIcon',
    expand_more: 'ChevronDownIcon',
    first_page: 'ChevronDoubleLeftIcon',
    folder_zip: 'ArchiveBoxIcon',
    image: 'PhotoIcon',
    inbox: 'InboxIcon',
    info: 'InformationCircleIcon',
    last_page: 'ChevronDoubleRightIcon',
    more_horiz: 'EllipsisHorizontalIcon',
    notifications: 'BellIcon',
    open_in_new: 'ArrowTopRightOnSquareIcon',
    picture_as_pdf: 'DocumentIcon',
    priority_high: 'ExclamationCircleIcon',
    remove: 'MinusIcon',
    schedule: 'ClockIcon',
    search: 'MagnifyingGlassIcon',
    search_off: 'MagnifyingGlassMinusIcon',
    star: 'StarIcon',
    swap_vert: 'ArrowsUpDownIcon',
    table_chart: 'TableCellsIcon',
    video_file: 'FilmIcon',
    warning: 'ExclamationTriangleIcon',
    home: 'HomeIcon',
    settings: 'Cog6ToothIcon',
    person: 'UserIcon',
    group: 'UserGroupIcon',
    folder: 'FolderIcon',
    mail: 'EnvelopeIcon',
    edit: 'PencilSquareIcon',
    delete: 'TrashIcon',
    download: 'ArrowDownTrayIcon',
    logout: 'ArrowRightStartOnRectangleIcon',
    bar_chart: 'ChartBarIcon',
    dashboard: 'Squares2X2Icon',
    favorite: 'HeartIcon',
  },
  phosphor: {
    add: 'plus',
    arrow_downward: 'arrow-down',
    arrow_downward_alt: 'arrow-down',
    arrow_drop_down: 'caret-down',
    arrow_drop_up: 'caret-up',
    arrow_left_alt: 'arrow-left',
    arrow_right_alt: 'arrow-right',
    arrow_upward: 'arrow-up',
    arrow_upward_alt: 'arrow-up',
    attach_file: 'paperclip',
    audio_file: 'file-audio',
    calendar_today: 'calendar-blank',
    check: 'check',
    check_circle: 'check-circle',
    chevron_left: 'caret-left',
    chevron_right: 'caret-right',
    close: 'x',
    cloud_upload: 'cloud-arrow-up',
    code: 'code',
    colorize: 'eyedropper',
    description: 'file-text',
    error: 'warning-circle',
    expand_less: 'caret-up',
    expand_more: 'caret-down',
    first_page: 'caret-line-left',
    folder_zip: 'file-zip',
    image: 'image',
    inbox: 'tray',
    info: 'info',
    last_page: 'caret-line-right',
    more_horiz: 'dots-three',
    notifications: 'bell',
    open_in_new: 'arrow-square-out',
    picture_as_pdf: 'file-pdf',
    priority_high: 'exclamation-mark',
    remove: 'minus',
    schedule: 'clock',
    search: 'magnifying-glass',
    search_off: 'magnifying-glass-minus',
    star: 'star',
    swap_vert: 'arrows-down-up',
    table_chart: 'table',
    video_file: 'file-video',
    warning: 'warning',
    home: 'house',
    settings: 'gear',
    person: 'user',
    group: 'users',
    folder: 'folder',
    mail: 'envelope',
    edit: 'pencil-simple',
    delete: 'trash',
    download: 'download-simple',
    logout: 'sign-out',
    bar_chart: 'chart-bar',
    dashboard: 'squares-four',
    favorite: 'heart',
  },
  tabler: {
    add: 'plus',
    arrow_downward: 'arrow-down',
    arrow_downward_alt: 'arrow-down',
    arrow_drop_down: 'caret-down',
    arrow_drop_up: 'caret-up',
    arrow_left_alt: 'arrow-left',
    arrow_right_alt: 'arrow-right',
    arrow_upward: 'arrow-up',
    arrow_upward_alt: 'arrow-up',
    attach_file: 'paperclip',
    audio_file: 'file-music',
    calendar_today: 'calendar',
    check: 'check',
    check_circle: 'circle-check',
    chevron_left: 'chevron-left',
    chevron_right: 'chevron-right',
    close: 'x',
    cloud_upload: 'cloud-upload',
    code: 'code',
    colorize: 'color-picker',
    description: 'file-text',
    error: 'alert-circle',
    expand_less: 'chevron-up',
    expand_more: 'chevron-down',
    first_page: 'chevron-left-pipe',
    folder_zip: 'file-zip',
    image: 'photo',
    inbox: 'inbox',
    info: 'info-circle',
    last_page: 'chevron-right-pipe',
    more_horiz: 'dots',
    notifications: 'bell',
    open_in_new: 'external-link',
    picture_as_pdf: 'file-type-pdf',
    priority_high: 'exclamation-mark',
    remove: 'minus',
    schedule: 'clock',
    search: 'search',
    search_off: 'search-off',
    star: 'star',
    swap_vert: 'arrows-sort',
    table_chart: 'table',
    video_file: 'movie',
    warning: 'alert-triangle',
    home: 'home',
    settings: 'settings',
    person: 'user',
    group: 'users',
    folder: 'folder',
    mail: 'mail',
    edit: 'pencil',
    delete: 'trash',
    download: 'download',
    logout: 'logout',
    bar_chart: 'chart-bar',
    dashboard: 'layout-dashboard',
    favorite: 'heart',
  },
  remix: {
    add: 'add',
    arrow_downward: 'arrow-down',
    arrow_downward_alt: 'arrow-down',
    arrow_drop_down: 'arrow-drop-down',
    arrow_drop_up: 'arrow-drop-up',
    arrow_left_alt: 'arrow-left',
    arrow_right_alt: 'arrow-right',
    arrow_upward: 'arrow-up',
    arrow_upward_alt: 'arrow-up',
    attach_file: 'attachment',
    audio_file: 'file-music',
    calendar_today: 'calendar',
    check: 'check',
    check_circle: 'checkbox-circle',
    chevron_left: 'arrow-left-s',
    chevron_right: 'arrow-right-s',
    close: 'close',
    cloud_upload: 'upload-cloud-2',
    code: 'code-s-slash',
    colorize: 'drop',
    description: 'file-text',
    error: 'error-warning',
    expand_less: 'arrow-up-s',
    expand_more: 'arrow-down-s',
    first_page: 'skip-left',
    folder_zip: 'file-zip',
    image: 'image',
    inbox: 'inbox',
    info: 'information',
    last_page: 'skip-right',
    more_horiz: 'more',
    notifications: 'notification-3',
    open_in_new: 'external-link',
    picture_as_pdf: 'file-pdf',
    priority_high: 'alert',
    remove: 'subtract',
    schedule: 'time',
    search: 'search',
    search_off: 'search',
    star: 'star',
    swap_vert: 'arrow-up-down',
    table_chart: 'table',
    video_file: 'file-video',
    warning: 'alert',
    home: 'home-5',
    settings: 'settings-3',
    person: 'user',
    group: 'group',
    folder: 'folder',
    mail: 'mail',
    edit: 'pencil',
    delete: 'delete-bin',
    download: 'download',
    logout: 'logout-box-r',
    bar_chart: 'bar-chart',
    dashboard: 'dashboard',
    favorite: 'heart',
  },
  fontawesome: {
    add: 'plus',
    arrow_downward: 'arrow-down',
    arrow_downward_alt: 'arrow-down',
    arrow_drop_down: 'caret-down',
    arrow_drop_up: 'caret-up',
    arrow_left_alt: 'arrow-left',
    arrow_right_alt: 'arrow-right',
    arrow_upward: 'arrow-up',
    arrow_upward_alt: 'arrow-up',
    attach_file: 'paperclip',
    audio_file: 'file-audio',
    calendar_today: 'calendar',
    check: 'check',
    check_circle: 'circle-check',
    chevron_left: 'chevron-left',
    chevron_right: 'chevron-right',
    close: 'xmark',
    cloud_upload: 'cloud-arrow-up',
    code: 'code',
    colorize: 'eye-dropper',
    description: 'file-lines',
    error: 'circle-exclamation',
    expand_less: 'chevron-up',
    expand_more: 'chevron-down',
    first_page: 'backward-step',
    folder_zip: 'file-zipper',
    image: 'image',
    inbox: 'inbox',
    info: 'circle-info',
    last_page: 'forward-step',
    more_horiz: 'ellipsis',
    notifications: 'bell',
    open_in_new: 'arrow-up-right-from-square',
    picture_as_pdf: 'file-pdf',
    priority_high: 'exclamation',
    remove: 'minus',
    schedule: 'clock',
    search: 'magnifying-glass',
    search_off: 'magnifying-glass-minus',
    star: 'star',
    swap_vert: 'sort',
    table_chart: 'table',
    video_file: 'file-video',
    warning: 'triangle-exclamation',
    home: 'house',
    settings: 'gear',
    person: 'user',
    group: 'users',
    folder: 'folder',
    mail: 'envelope',
    edit: 'pen',
    delete: 'trash',
    download: 'download',
    logout: 'right-from-bracket',
    bar_chart: 'chart-column',
    dashboard: 'table-cells-large',
    favorite: 'heart',
  },
  bootstrap: {
    add: 'plus',
    arrow_downward: 'arrow-down',
    arrow_downward_alt: 'arrow-down',
    arrow_drop_down: 'caret-down-fill',
    arrow_drop_up: 'caret-up-fill',
    arrow_left_alt: 'arrow-left',
    arrow_right_alt: 'arrow-right',
    arrow_upward: 'arrow-up',
    arrow_upward_alt: 'arrow-up',
    attach_file: 'paperclip',
    audio_file: 'file-earmark-music',
    calendar_today: 'calendar',
    check: 'check-lg',
    check_circle: 'check-circle',
    chevron_left: 'chevron-left',
    chevron_right: 'chevron-right',
    close: 'x-lg',
    cloud_upload: 'cloud-arrow-up',
    code: 'code',
    colorize: 'eyedropper',
    description: 'file-earmark-text',
    error: 'exclamation-circle',
    expand_less: 'chevron-up',
    expand_more: 'chevron-down',
    first_page: 'chevron-bar-left',
    folder_zip: 'file-earmark-zip',
    image: 'image',
    inbox: 'inbox',
    info: 'info-circle',
    last_page: 'chevron-bar-right',
    more_horiz: 'three-dots',
    notifications: 'bell',
    open_in_new: 'box-arrow-up-right',
    picture_as_pdf: 'file-earmark-pdf',
    priority_high: 'exclamation-lg',
    remove: 'dash-lg',
    schedule: 'clock',
    search: 'search',
    search_off: 'search',
    star: 'star',
    swap_vert: 'arrow-down-up',
    table_chart: 'table',
    video_file: 'file-earmark-play',
    warning: 'exclamation-triangle',
    home: 'house',
    settings: 'gear',
    person: 'person',
    group: 'people',
    folder: 'folder',
    mail: 'envelope',
    edit: 'pencil',
    delete: 'trash',
    download: 'download',
    logout: 'box-arrow-right',
    bar_chart: 'bar-chart',
    dashboard: 'grid',
    favorite: 'heart',
  },
} satisfies Record<string, Record<AliasedIconName, string>>
