/**
 * The preview's heroicons components, imported one by one so the bundle holds these drawings and
 * no others. Keep in step with `ICON_ALIASES.heroicons` in `../iconAliases.ts`.
 */
import {
  ArchiveBoxIcon,
  ArrowDownIcon,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpIcon,
  ArrowsUpDownIcon,
  BellIcon,
  CalendarIcon,
  ChartBarIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  CloudArrowUpIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  DocumentIcon,
  DocumentTextIcon,
  EllipsisHorizontalIcon,
  EnvelopeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeDropperIcon,
  FilmIcon,
  FolderIcon,
  HeartIcon,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MinusIcon,
  MusicalNoteIcon,
  PaperClipIcon,
  PencilSquareIcon,
  PhotoIcon,
  PlusIcon,
  Squares2X2Icon,
  StarIcon,
  TableCellsIcon,
  TrashIcon,
  UserGroupIcon,
  UserIcon,
  XMarkIcon,
} from '@heroicons/vue/24/outline'

import type { AliasedIconName } from '../iconAliases'

import type { Component } from 'vue'

export const components: Record<AliasedIconName, Component> = {
  add: PlusIcon,
  arrow_downward: ArrowDownIcon,
  arrow_downward_alt: ArrowDownIcon,
  arrow_drop_down: ChevronDownIcon,
  arrow_drop_up: ChevronUpIcon,
  arrow_left_alt: ArrowLeftIcon,
  arrow_right_alt: ArrowRightIcon,
  arrow_upward: ArrowUpIcon,
  arrow_upward_alt: ArrowUpIcon,
  attach_file: PaperClipIcon,
  audio_file: MusicalNoteIcon,
  calendar_today: CalendarIcon,
  check: CheckIcon,
  check_circle: CheckCircleIcon,
  chevron_left: ChevronLeftIcon,
  chevron_right: ChevronRightIcon,
  close: XMarkIcon,
  cloud_upload: CloudArrowUpIcon,
  code: CodeBracketIcon,
  colorize: EyeDropperIcon,
  description: DocumentTextIcon,
  error: ExclamationCircleIcon,
  expand_less: ChevronUpIcon,
  expand_more: ChevronDownIcon,
  first_page: ChevronDoubleLeftIcon,
  folder_zip: ArchiveBoxIcon,
  image: PhotoIcon,
  inbox: InboxIcon,
  info: InformationCircleIcon,
  last_page: ChevronDoubleRightIcon,
  more_horiz: EllipsisHorizontalIcon,
  notifications: BellIcon,
  open_in_new: ArrowTopRightOnSquareIcon,
  picture_as_pdf: DocumentIcon,
  priority_high: ExclamationCircleIcon,
  remove: MinusIcon,
  schedule: ClockIcon,
  search: MagnifyingGlassIcon,
  search_off: MagnifyingGlassMinusIcon,
  star: StarIcon,
  swap_vert: ArrowsUpDownIcon,
  table_chart: TableCellsIcon,
  video_file: FilmIcon,
  warning: ExclamationTriangleIcon,
  home: HomeIcon,
  settings: Cog6ToothIcon,
  person: UserIcon,
  group: UserGroupIcon,
  folder: FolderIcon,
  mail: EnvelopeIcon,
  edit: PencilSquareIcon,
  delete: TrashIcon,
  download: ArrowDownTrayIcon,
  logout: ArrowRightStartOnRectangleIcon,
  bar_chart: ChartBarIcon,
  dashboard: Squares2X2Icon,
  favorite: HeartIcon,
}
