/**
 * The preview's lucide components, imported one by one so the bundle holds these drawings and
 * no others. Keep in step with `ICON_ALIASES.lucide` in `../iconAliases.ts`.
 */
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Bell,
  Calendar,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  Clock,
  CloudUpload,
  Code,
  Download,
  Ellipsis,
  ExternalLink,
  FileArchive,
  FileMusic,
  FileText,
  FileType,
  FileVideoCamera,
  Folder,
  Heart,
  House,
  Image,
  Inbox,
  Info,
  LayoutDashboard,
  LogOut,
  Mail,
  Minus,
  Paperclip,
  Pencil,
  Pipette,
  Plus,
  Search,
  SearchX,
  Settings,
  Star,
  Table,
  Trash,
  TriangleAlert,
  User,
  Users,
  X,
} from '@lucide/vue'

import type { AliasedIconName } from '../iconAliases'

import type { Component } from 'vue'

export const components: Record<AliasedIconName, Component> = {
  add: Plus,
  arrow_downward: ArrowDown,
  arrow_downward_alt: ArrowDown,
  arrow_drop_down: ChevronDown,
  arrow_drop_up: ChevronUp,
  arrow_left_alt: ArrowLeft,
  arrow_right_alt: ArrowRight,
  arrow_upward: ArrowUp,
  arrow_upward_alt: ArrowUp,
  attach_file: Paperclip,
  audio_file: FileMusic,
  calendar_today: Calendar,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_upload: CloudUpload,
  code: Code,
  colorize: Pipette,
  description: FileText,
  error: CircleAlert,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  first_page: ChevronFirst,
  folder_zip: FileArchive,
  image: Image,
  inbox: Inbox,
  info: Info,
  last_page: ChevronLast,
  more_horiz: Ellipsis,
  notifications: Bell,
  open_in_new: ExternalLink,
  picture_as_pdf: FileType,
  priority_high: CircleAlert,
  remove: Minus,
  schedule: Clock,
  search: Search,
  search_off: SearchX,
  star: Star,
  swap_vert: ArrowUpDown,
  table_chart: Table,
  video_file: FileVideoCamera,
  warning: TriangleAlert,
  home: House,
  settings: Settings,
  person: User,
  group: Users,
  folder: Folder,
  mail: Mail,
  edit: Pencil,
  delete: Trash,
  download: Download,
  logout: LogOut,
  bar_chart: ChartColumn,
  dashboard: LayoutDashboard,
  favorite: Heart,
}
